name: Formatting Check

on:
  push:
  pull_request:

jobs:
  format-check:
    name: Check for formatting errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Run formatting checks
        run: |
          bun install --frozen-lockfile
          bun run eslint --fix-dry-run --ignore-pattern dist/
          bun run format:cspell
          bun run prettier --check .
